title: Andreas Warntjen # your name (or website title) here
logo: "/images/Warntjen-Portrait.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Data Scientist 
  <br><br>
  <a href="https://warntjen.github.io/index.html">Start</a> <br>
  <a href="https://warntjen.github.io/profil.html">Über mich</a> <br>
  <a href="https://warntjen.github.io/tutorials.html">Tutorials</a> <br>
  
theme: jekyll-theme-minimal
