title: Andreas Warntjen # your name (or website title) here
logo: "/images/Warntjen-Portrait.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Data Scientist 
  <br><br>
  <a href="https://r2python.github.io/index.html">Über mich</a> <br>
  <a href="https://r2python.github.io/tutorials.html">Tutorials</a> <br>
  <br>
  <a href="https://www.linkedin.com/in/warntjen/">Mein Profil auf LinkedIn</a> <br>
  <a href="https://www.xing.com/profile/Andreas_Warntjen">Mein Profil auf XING</a> 

theme: jekyll-theme-minimal
